name: Periodic healthcheck to url

on: # later put here scheduled time
  schedule:
    - cron: '30 2 * * 6'
  branches:
    - master

jobs:
  scheduled_healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: check the deployed service url
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://olivias-pokedex-app.fly.dev/



# toJSON(github.event.commits.*.message) palauttaa listan
# kaikista commit messageista
# joinaa nää yhteen
# jos contains #skips niin skippaa tag